source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', '~> 4.1', '>= 4.1.1'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'ckeditor', '~> 4.1', '>= 4.1.6'
gem 'paperclip', '~> 4.3', '>= 4.3.6'
gem 'carrierwave', '~> 0.11.2'
gem 'dragonfly', '~> 1.0', '>= 1.0.12'
gem 'refile', '~> 0.6.2'
gem 'refile-mini_magick', '~> 0.2.0'
gem 'jquery-turbolinks', '~> 2.1'
gem 'masonry-rails', '~> 0.2.4'



group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'

  gem 'spring'
end

